import type { ModelDefinition } from '../kie/types.ts'

export const DEDICATED_MODELS: ModelDefinition[] = [
  {
    id: 'suno/music',
    model: 'suno/music',
    title: 'Suno — Create a song',
    category: 'audio',
    provider: 'suno',
    operation: 'generate',
    useCase: 'Song',
    tags: ['music', 'lyrics', 'instrumental'],
    docsUrl: 'https://docs.kie.ai/suno-api/generate-music',
    fields: [
      { name: 'customMode', type: 'boolean', label: 'Specify lyrics & style', default: true },
      { name: 'instrumental', type: 'boolean', label: 'Instrumental', default: false },
      { name: 'prompt', type: 'textarea', label: 'Lyrics / song idea', maxLength: 5000 },
      { name: 'style', type: 'textarea', label: 'Style', description: 'Genre, tempo, instruments, voice quality, etc.', maxLength: 1000 },
      { name: 'title', type: 'string', label: 'Title', maxLength: 100 },
      { name: 'model', type: 'enum', label: 'Suno model', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
      { name: 'negativeTags', type: 'string', label: 'Elements to avoid', maxLength: 500 },
      { name: 'personaId', type: 'string', label: 'Persona ID', description: 'Auto-filled when a Persona is selected from the asset library' },
    ],
  },
  {
    id: 'suno/extend',
    model: 'suno/extend',
    title: 'Suno — Continue a song',
    category: 'audio',
    provider: 'suno',
    operation: 'extend',
    useCase: 'Song',
    tags: ['music', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'audioId', type: 'string', label: 'Original Audio ID', required: true },
      { name: 'continueAt', type: 'number', label: 'Continue at (seconds)', required: true, min: 0, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: 'Continuation lyrics / instructions', required: true },
      { name: 'style', type: 'string', label: 'Style' },
      { name: 'title', type: 'string', label: 'Title' },
      { name: 'model', type: 'enum', label: 'Suno model', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/upload-extend',
    model: 'suno/upload-extend',
    title: 'Suno — Continue from uploaded audio',
    category: 'audio',
    provider: 'suno',
    operation: 'upload-extend',
    useCase: 'Song',
    tags: ['music', 'upload', 'extend'],
    fields: [
      { name: 'uploadUrl', type: 'reference', label: 'Audio source', required: true, accept: 'audio/*', scalar: true, mentionStyle: 'none', maxItems: 1, maxDurationSec: 480 },
      { name: 'continueAt', type: 'number', label: 'Continue at (seconds)', required: true, min: 0, max: 480, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: 'Continuation lyrics / instructions', required: true },
      { name: 'style', type: 'string', label: 'Style' },
      { name: 'title', type: 'string', label: 'Title' },
      { name: 'model', type: 'enum', label: 'Suno model', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/upload-cover',
    model: 'suno/upload-cover',
    title: 'Suno — Cover an audio track',
    category: 'audio',
    provider: 'suno',
    operation: 'upload-cover',
    useCase: 'Song',
    tags: ['music', 'upload', 'cover'],
    docsUrl: 'https://docs.kie.ai/suno-api/upload-and-cover-audio',
    fields: [
      { name: 'uploadUrl', type: 'reference', label: 'Original audio', required: true, accept: 'audio/*', scalar: true, mentionStyle: 'none', maxItems: 1, maxDurationSec: 480 },
      { name: 'customMode', type: 'boolean', label: 'Specify lyrics & style', default: true },
      { name: 'instrumental', type: 'boolean', label: 'Instrumental', default: false },
      { name: 'prompt', type: 'textarea', label: 'Lyrics / cover instructions', maxLength: 5000 },
      { name: 'style', type: 'textarea', label: 'Style', maxLength: 1000 },
      { name: 'title', type: 'string', label: 'Title', maxLength: 100 },
      { name: 'model', type: 'enum', label: 'Suno model', enum: ['V5', 'V4_5PLUS', 'V4_5', 'V4'], default: 'V5' },
    ],
  },
  {
    id: 'suno/lyrics',
    model: 'suno/lyrics',
    title: 'Suno — Write lyrics',
    category: 'audio',
    provider: 'suno',
    operation: 'lyrics',
    useCase: 'Song',
    tags: ['music', 'lyrics', 'writing'],
    docsUrl: 'https://docs.kie.ai/suno-api/generate-lyrics',
    fields: [
      { name: 'prompt', type: 'textarea', label: 'Lyrics theme / instructions', required: true, maxLength: 2000 },
    ],
  },
  {
    id: 'suno/replace-section',
    model: 'suno/replace-section',
    title: 'Suno — Replace a section',
    category: 'audio',
    provider: 'suno',
    operation: 'replace-section',
    useCase: 'Song',
    tags: ['music', 'edit'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'audioId', type: 'string', label: 'Original Audio ID', required: true },
      { name: 'infillStartS', type: 'number', label: 'Start (seconds)', required: true, min: 0, step: 0.1 },
      { name: 'infillEndS', type: 'number', label: 'End (seconds)', required: true, min: 6, step: 0.1 },
      { name: 'prompt', type: 'textarea', label: 'Replacement lyrics / content', required: true },
      { name: 'tags', type: 'string', label: 'Style', required: true },
      { name: 'title', type: 'string', label: 'Title', required: true },
      { name: 'negativeTags', type: 'string', label: 'Elements to avoid' },
      { name: 'fullLyrics', type: 'textarea', label: 'Full lyrics (optional)' },
      { name: '_duration', type: 'number', label: 'Original audio length (for validation)', min: 0 },
    ],
  },
  {
    id: 'market/elevenlabs-dialogue',
    model: 'elevenlabs/text-to-dialogue-v3',
    title: 'ElevenLabs — Create dialogue',
    category: 'audio',
    provider: 'market',
    operation: 'generate',
    useCase: 'Dialogue',
    tags: ['speech', 'dialogue'],
    docsUrl: 'https://docs.kie.ai/market/elevenlabs/text-to-dialogue-v3',
    fields: [
      { name: 'dialogue', type: 'json', label: 'Speaker lines', required: true, description: '[{"text":"hello","voice":"voice-id"}]' },
      { name: 'stability', type: 'number', label: 'Voice stability', min: 0, max: 1, step: 0.5, default: 0.5 },
      { name: 'language_code', type: 'string', label: 'Language code', description: 'e.g. ja. Auto-detected if empty' },
    ],
  },
  {
    id: 'market/elevenlabs-tts',
    model: 'elevenlabs/text-to-speech-multilingual-v2',
    title: 'ElevenLabs — Narration',
    category: 'audio',
    provider: 'market',
    operation: 'generate',
    useCase: 'Narration',
    tags: ['speech', 'tts', 'multilingual'],
    docsUrl: 'https://docs.kie.ai/market/elevenlabs/text-to-speech-multilingual-v2',
    fields: [
      { name: 'text', type: 'textarea', label: 'Script', required: true, maxLength: 20000, description: 'Split into segments of up to 5000 characters by blank lines' },
      { name: 'voice', type: 'string', label: 'Voice ID', required: true },
      { name: 'stability', type: 'number', label: 'Voice stability', min: 0, max: 1, step: 0.05, default: 0.5 },
      { name: 'similarity_boost', type: 'number', label: 'Voice similarity', min: 0, max: 1, step: 0.05, default: 0.75 },
      { name: 'style', type: 'number', label: 'Expressiveness', min: 0, max: 1, step: 0.05, default: 0 },
      { name: 'speed', type: 'number', label: 'Speaking speed', min: 0.7, max: 1.2, step: 0.05, default: 1 },
      { name: 'timestamps', type: 'boolean', label: 'Word timestamps', default: true },
      { name: 'previous_text', type: 'textarea', label: 'Previous context', description: 'Automatically connected during segment generation', maxLength: 5000 },
      { name: 'next_text', type: 'textarea', label: 'Next context', description: 'Automatically connected during segment generation', maxLength: 5000 },
      { name: 'language_code', type: 'string', label: 'Language code', description: 'e.g. ja. Auto-detected if empty' },
    ],
  },
  {
    id: 'veo/generate',
    model: 'veo',
    title: 'Veo — Create a video',
    category: 'video',
    provider: 'veo',
    operation: 'generate',
    useCase: 'Video generation',
    tags: ['veo', 'video'],
    fields: [
      { name: 'prompt', type: 'textarea', label: 'Video instructions', required: true },
      { name: 'imageUrls', type: 'reference', label: 'Reference images', accept: 'image/*', maxItems: 3, mentionStyle: 'none' },
      { name: 'model', type: 'enum', label: 'Veo model', enum: ['veo3_fast', 'veo3'], default: 'veo3_fast' },
      { name: 'aspectRatio', type: 'enum', label: 'Aspect ratio', enum: ['16:9', '9:16'], default: '16:9' },
    ],
  },
  {
    id: 'veo/extend',
    model: 'veo/extend',
    title: 'Veo — Extend a video',
    category: 'video',
    provider: 'veo',
    operation: 'extend',
    useCase: 'Video editing',
    tags: ['veo', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'prompt', type: 'textarea', label: 'Continuation instructions', required: true },
    ],
  },
  {
    id: 'veo/1080p',
    model: 'veo/1080p',
    title: 'Veo — Convert to 1080p',
    category: 'video',
    provider: 'veo',
    operation: 'upscale-1080p',
    useCase: 'Upscaling',
    tags: ['veo', '1080p', 'upscale'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'index', type: 'number', label: 'Video index', required: true, min: 0, max: 3, step: 1, default: 0 },
    ],
  },
  {
    id: 'veo/4k',
    model: 'veo/4k',
    title: 'Veo — Convert to 4K',
    category: 'video',
    provider: 'veo',
    operation: 'upscale-4k',
    useCase: 'Upscaling',
    tags: ['veo', '4k', 'upscale'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'index', type: 'number', label: 'Video index', required: true, min: 0, max: 3, step: 1, default: 0 },
    ],
  },
  {
    id: 'runway/generate',
    model: 'runway',
    title: 'Runway — Create a video',
    category: 'video',
    provider: 'runway',
    operation: 'generate',
    useCase: 'Video generation',
    tags: ['runway', 'video'],
    fields: [
      { name: 'prompt', type: 'textarea', label: 'Video instructions', required: true },
      { name: 'imageUrl', type: 'reference', label: 'Start image', accept: 'image/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'duration', type: 'enum', label: 'Duration', enum: ['5', '10'], default: '5' },
      { name: 'quality', type: 'enum', label: 'Quality', enum: ['720p', '1080p'], default: '720p' },
      { name: 'aspectRatio', type: 'enum', label: 'Aspect ratio', enum: ['16:9', '9:16', '1:1'], default: '16:9' },
    ],
  },
  {
    id: 'runway/extend',
    model: 'runway/extend',
    title: 'Runway — Extend a video',
    category: 'video',
    provider: 'runway',
    operation: 'extend',
    useCase: 'Video editing',
    tags: ['runway', 'extend'],
    fields: [
      { name: 'taskId', type: 'string', label: 'Original task ID', required: true },
      { name: 'videoId', type: 'string', label: 'Original Video ID', required: true },
      { name: 'prompt', type: 'textarea', label: 'Continuation instructions', required: true },
    ],
  },
  {
    id: 'runway/aleph',
    model: 'runway/aleph',
    title: 'Runway Aleph — Modify a video',
    category: 'video',
    provider: 'runway',
    operation: 'aleph',
    useCase: 'Video editing',
    tags: ['runway', 'aleph', 'edit'],
    docsUrl: 'https://docs.kie.ai/runway-api/generate-aleph-video',
    fields: [
      { name: '_parentTaskId', type: 'string', label: 'Parent task ID' },
      { name: 'videoUrl', type: 'reference', label: 'Source video', required: true, accept: 'video/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'prompt', type: 'textarea', label: 'What to change', required: true },
    ],
  },
  {
    id: 'market/volcengine-lip-sync',
    model: 'volcengine/video-to-video-lip-sync',
    title: 'Volcengine — Lip-sync a video',
    category: 'video',
    provider: 'market',
    operation: 'generate',
    useCase: 'Lip-sync',
    tags: ['video', 'audio', 'lip-sync'],
    docsUrl: 'https://docs.kie.ai/market/volcengine/video-to-video-lip-sync',
    fields: [
      { name: 'video_url', type: 'reference', label: 'Video', required: true, accept: 'video/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
      { name: 'audio_url', type: 'reference', label: 'Audio', required: true, accept: 'audio/*', scalar: true, maxItems: 1, mentionStyle: 'none' },
    ],
  },
]
